### ISSUE TITLE
Queryx Bind ...interface{} 

### ISSUE THREAD

**Issue by kynetiv** [Guilospanck/igocqlx#1]
Hi, thanks so much for these interfaces! I'm really happy to find this work and examples for mocking.

Testing it out I did find a small issue when I `Bind` a value to a Query statement.

Here's a quick example of my code:

```go
myId := "1"
row := SomeType{}
q := session.Query("SELECT * FROM my_table WHERE id = ?", nil).Bind(&myId)
if err := q.Iter().Unsafe().Get(&row); err != nil {
  fmt.Printf("ERR: %s, err) // "ERR: can not marshal []interface {} into varchar"
}
```

Essentially, since the igocqlx's `Bind` takes a variadic parameter, and the underlying gocqlx's `Bind` does too, I _think_ your Bind needs to "unwrap" or spread the slice values when passing them to gocqlx's `Bind`... If not, the executed statement errors with the above marshal error.

I tried to simulate the difference in types each function receive  in this [playground](https://go.dev/play/p/gqmp40n9i9i?v=goprev).

I will open a quick PR to fix it.

**Comment by Guilospanck** [comment]
Hey, thanks for the PR! Approved it.
Since I started this "library" from scratch I knew there would be some fixes to do.

There will be more in the future, for sure. Software development is a never ending process.

Collaborations are welcome 😁
